name: bus_counter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.17.4
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.1
  go_router: ^14.1.3
  image_picker: ^1.1.1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  logger: ^2.3.0
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  skeletons: ^0.0.3
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
