// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB796hUOJmtcUK-p5WkOyP-S59tCEfKzc',
    appId: '1:12470503756:android:786eb916c38509e15d27e9',
    messagingSenderId: '12470503756',
    projectId: 'gamecounter-734be',
    storageBucket: 'gamecounter-734be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1FC6Htc24hyhEm4ApaBFw0UDntMrmjTw',
    appId: '1:12470503756:ios:5fa89178fa0f6eb05d27e9',
    messagingSenderId: '12470503756',
    projectId: 'gamecounter-734be',
    storageBucket: 'gamecounter-734be.appspot.com',
    iosBundleId: 'com.hswoo.busdrivder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4GfAg_V1ebMuLFRb_ufHmJMEBUuUVHEk',
    appId: '1:12470503756:web:62f8016d327a1d045d27e9',
    messagingSenderId: '12470503756',
    projectId: 'gamecounter-734be',
    authDomain: 'gamecounter-734be.firebaseapp.com',
    storageBucket: 'gamecounter-734be.appspot.com',
  );

}